name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/laravel-api ./API
          docker push ${{ secrets.DOCKER_USERNAME }}/laravel-api

      - name: Build and push Client image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nuxt-client ./Client
          docker push ${{ secrets.DOCKER_USERNAME }}/nuxt-client
